In [ ]:
import numpy as np
import pandas as pd

Step 2. Import the popular ‘iris’ dataset from the below address. And then check the header of the dataset.
https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = pd.read_csv(url)
iris.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

Step 3. You can see that the column headers are missing in the above case. Therefore this step is related to the creation of column heads for the dataset. Write code to create 5 column heads. Next write a code to display or show the headers.
1. sepal_length
2. sepal_width
3. petal_length
4. petal_width
5. class

In [ ]:
iris = pd.read_csv(url, header = None)
iris.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [ ]:
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Step 4. Write a code to check if there are any missing values in the dataframe?

In [ ]:
iris.isnull().values.any()

False

In [ ]:
iris.isnull().sum().sum()

0

Step 5. Write a code to set the values of the rows 10 to 29 of the column 'petal_length' to NaN.

In [ ]:
iris.iloc[9:29, 2] = np.nan

Step 6. Now again, check if there is any missing values (NaN) in the dataframe? Count, how many missing values.

In [ ]:
iris.isnull().values.any()

True

In [ ]:
iris.isnull().sum().sum()

20

Step 7. Substitute the NaN values to 10.0

In [ ]:
iris.fillna(10.0, inplace = True)